pipeline{

    parameters{
        choice(name: 'terraformAction',choices: ['apply','destroy'],description: 'Choose your terraform action to perform')
    }


    environment{
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    agent any

    stages{
        stage('checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/ManojKRISHNAPPA/Opskillsup.git'
            }
        }

        stage('plan'){
            steps{
                sh '''
                    pwd
                    cd 04-PROJECT-1/
                    terraform init
                    terraform plan -out tfplan
                    terraform show -no-color tfplan > tfplan.txt
                '''
            }
        }
    }

}