pipeline{

    parameters{
        choice(name: 'terraformAction',choice: ['apply','destroy'],description: 'Choose your terraform action to perform')
    }


    environment{
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    agent any

    stages{
        stage('checkout'){
            steps{
                git branch: 'main', URL: 'https://github.com/ManojKRISHNAPPA/Opskillsup.git'
            }
        }

        // stage()
    }

}